// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/analytics" | "/attendance" | "/credits" | "/dashboard" | "/database-setup" | "/history" | "/tasks"
type AppRouteHandlerRoutes = "/api/admin/audit-logs" | "/api/admin/performance" | "/api/attendance" | "/api/attendance/[id]" | "/api/attendance/auto-reset" | "/api/attendance/reset" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/compliance/gdpr" | "/api/credits" | "/api/credits/[id]" | "/api/database/backup" | "/api/database/info" | "/api/database/setup" | "/api/employees" | "/api/employees/[id]" | "/api/health" | "/api/history" | "/api/settings" | "/api/stats" | "/api/tasks" | "/api/tasks/[id]" | "/api/user/delete" | "/api/user/export"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/analytics": {}
  "/api/admin/audit-logs": {}
  "/api/admin/performance": {}
  "/api/attendance": {}
  "/api/attendance/[id]": { "id": string; }
  "/api/attendance/auto-reset": {}
  "/api/attendance/reset": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/compliance/gdpr": {}
  "/api/credits": {}
  "/api/credits/[id]": { "id": string; }
  "/api/database/backup": {}
  "/api/database/info": {}
  "/api/database/setup": {}
  "/api/employees": {}
  "/api/employees/[id]": { "id": string; }
  "/api/health": {}
  "/api/history": {}
  "/api/settings": {}
  "/api/stats": {}
  "/api/tasks": {}
  "/api/tasks/[id]": { "id": string; }
  "/api/user/delete": {}
  "/api/user/export": {}
  "/attendance": {}
  "/credits": {}
  "/dashboard": {}
  "/database-setup": {}
  "/history": {}
  "/tasks": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
